# CHAPTER 1___DATA  PREPROCESSING___



# Step by Step Code

### Importing libraries and reading the dataset

In [64]:
#Data preprocessing

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Read the input dataset
data = pd.read_csv("data2.csv")
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

###   Independent and dependent variable vector

In [65]:
X = data.iloc[:,:-1].values         #we will take all the rows(:), we will take all the columns expect the last one(:-1)
Y = data.iloc[:,-1:].values         # country age salary is independent and purchased is dependent variable
print(X)
print(Y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
[['No']
 ['Yes']
 ['No']
 ['No']
 ['Yes']
 ['Yes']
 ['No']
 ['Yes']
 ['No']
 ['Yes']]


### Taking care of missing data

In [66]:
from sklearn.impute import SimpleImputer    #New version 0.20 replaces the previous sklearn.preprocessing.Imputer
imputer = SimpleImputer(strategy="mean")    #we have to first creat an object for SimpleImputer class
imputer = imputer.fit(X[:,1:3])             # To fit input or object to our X   { method- fit(X[,y])}
X[:,1:3] = imputer.transform(X[:,1:3])      # replace the missing data of our X by the mean of the column  
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

### Encode categorical data

In [67]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder_X = LabelEncoder()       #we have to first creat an object for Labelencoder class
X[:,0] = labelencoder_X.fit_transform(X[:,0])  #Encoded the countries as numaric values
print(X)                                       #Fit label encoder and return encoded labels

labelencoder_Y = LabelEncoder()       #we have to first creat an object for Labelencoder class
Y= labelencoder_Y.fit_transform(Y)  #Encoded the countries as numaric values
print(Y)                                       #Fit label encoder and return encoded labels

#DUMMY VARIABLES    [This creates a binary column for each catagory]

ct=ColumnTransformer([('ANonno',             # Just a name
                       OneHotEncoder(),      # The transformer class
                       [0])],                # The column(s)to be applied on
                     remainder='passthrough')# donot apply anything to the remaining columns
X=ct.fit_transform(X)
print(X)


[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 63777.77777777778]
 [0 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]
[0 1 0 0 1 1 0 1 0 1]
[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


D:\ANACONDA PYTHON\lib\site-packages\sklearn\preprocessing\_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### Splitting the data into training set and test set

In [70]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, train_size=0.8, random_state=0)
print(X_train)
print(Y_train)

[[0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
[1 1 1 0 1 0 0 1]


### Feature scaling

In [73]:
from sklearn.preprocessing import StandardScaler

sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)
print(X_train)
print(X_test)

[[-1.          2.64575131 -0.77459667  0.26306757  0.12381479]
 [ 1.         -0.37796447 -0.77459667 -0.25350148  0.46175632]
 [-1.         -0.37796447  1.29099445 -1.97539832 -1.53093341]
 [-1.         -0.37796447  1.29099445  0.05261351 -1.11141978]
 [ 1.         -0.37796447 -0.77459667  1.64058505  1.7202972 ]
 [-1.         -0.37796447  1.29099445 -0.0813118  -0.16751412]
 [ 1.         -0.37796447 -0.77459667  0.95182631  0.98614835]
 [ 1.         -0.37796447 -0.77459667 -0.59788085 -0.48214934]]
[[-1.          2.64575131 -0.77459667 -1.45882927 -0.90166297]
 [-1.          2.64575131 -0.77459667  1.98496442  2.13981082]]


## ALL CODE TOGATHER

In [75]:
#Data preprocessing

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Read the input dataset
data = pd.read_csv("data2.csv")
print(data)

X = data.iloc[:,:-1].values         #we will take all the rows(:), we will take all the columns expect the last one(:-1)
Y = data.iloc[:,-1:].values         # country age salary is independent and purchased is dependent variable
print(X)
print(Y)

from sklearn.impute import SimpleImputer    #New version 0.20 replaces the previous sklearn.preprocessing.Imputer
imputer = SimpleImputer(strategy="mean")    #we have to first creat an object for SimpleImputer class
imputer = imputer.fit(X[:,1:3])             # To fit input or object to our X   { method- fit(X[,y])}
X[:,1:3] = imputer.transform(X[:,1:3])      # replace the missing data of our X by the mean of the column  
print(X)


from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder_X = LabelEncoder()       #we have to first creat an object for Labelencoder class
X[:,0] = labelencoder_X.fit_transform(X[:,0])  #Encoded the countries as numaric values
print(X)                                       #Fit label encoder and return encoded labels

labelencoder_Y = LabelEncoder()       #we have to first creat an object for Labelencoder class
Y= labelencoder_Y.fit_transform(Y)  #Encoded the countries as numaric values
print(Y)                                       #Fit label encoder and return encoded labels

#DUMMY VARIABLES    [This creates a binary column for each catagory]

ct=ColumnTransformer([('ANonno',             # Just a name
                       OneHotEncoder(),      # The transformer class
                       [0])],                # The column(s)to be applied on
                     remainder='passthrough')# donot apply anything to the remaining columns
X=ct.fit_transform(X)
print(X)


from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, train_size=0.8, random_state=0)
print(X_train)
print(Y_train)


from sklearn.preprocessing import StandardScaler

sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)
print(X_train)
print(X_test)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
[['No']
 ['Yes']
 ['No']
 ['No']
 ['Yes']
 ['Yes']
 ['No']
 ['Yes']
 ['No']
 ['Yes']]
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]

D:\ANACONDA PYTHON\lib\site-packages\sklearn\preprocessing\_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[0 1 0 0 1 1 0 1 0 1]
[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
[[0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
[1 1 1 0 1 0 0 1]
[[-1.          2.64575131 -0.77459667  0.26306757  0.12381479]
 [ 1.         -0.37796447 -0.77459667 -0.25350148  0.46175632]
 [-1.         -0.37796447  1.29099445 -1.97539832 -1.53093341]
 [-1.         -0.37796447  1.29099445  0.05261351 -1.11141978]
 [ 1.         -0.37796447 -0.77459667  1.64058505  1.7202972 ]
 [-1.         -0.37796447  1.29099445 -0.0813118  -0.16751412]
 [ 1.         -0.37796447 -0.7